import type { NextPage } from "next";
import Head from "next/head";

import Nav from "../components/Nav";
import Hero from "../components/Hero";
import About from "../components/About";
import Projects from "../components/Project";
import Footer from "../components/Footer";

import { Button } from "@material-tailwind/react";

const Home: NextPage = () => {
  return (
    <div className="w-full max-w-screen-2xl mx-auto">
      <Head>
        <title>My portifolio - Florien Niyongabo </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconme.ico" />
      </Head>

      <main>
        <Nav />
        <Hero />
        <About />
        <Projects />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
