import Head from "next/head";

import Nav from "../components/Nav";
import Hero from "../components/Hero";
import About from "../components/About";
import Projects from "../components/Project";
import Footer from "../components/Footer";
import { Typography } from "@material-tailwind/react";
import { FC, useState } from "react";
import BackToTop from "../components/BackToTop";
import { ThemeContext } from "../utils/Contexts";
export const currentYear = () => {
  const year = new Date().getFullYear();
  return year;
};
const Home: FC = () => {
  const [theme, setTheme] = useState('light');

  const toggleTheme = () => {
    theme === "dark" ? setTheme('light') : setTheme('dark')
  }

  return (
    <ThemeContext.Provider value={theme}>
      <div className={`${theme === "dark" && "bg-darkSecondary"}`}>
        <div className={`w-full max-w-screen-2xl mx-auto`}>
          <Head>
            <title>My portifolio - Florien Niyongabo </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/faviconme.ico" />
          </Head>

          <main className={`space-y-4 lg:space-y-12`}>
            <Nav toggleTheme={() => toggleTheme()} />
            <Hero />
            <About />
            <Projects />
          </main>

          <Footer />

          <Typography className={`text-center text-black text-md py-4 ${theme === "dark" && "text-white"}`}>
            &copy; {currentYear()}. Crafted with ❤️ by Florien Niyongabo.  All rights reserved.
          </Typography>

          <BackToTop />
        </div>
      </div>
    </ThemeContext.Provider>
  );
};

export default Home;
